### ISSUE TITLE
Procedure or thought for moving candidates?

### ISSUE THREAD

**Issue by dennisdegreef** [jeroenvdgulik/awesome-talks#1]
Is there a procedure or thought for moving candidates to 'the list'?
What is the criteria?

**Comment by jeroenvdgulik** [comment]
The Criteria is mostly "was I impressed by the talk"

**Comment by dennisdegreef** [comment]
My contribution was the netflix talk, If you haven't seen it yet, I encourage you to :)

**Comment by jeroenvdgulik** [comment]
Done and Done
